version: '3.8'

services:
  mariadb:
    container_name: MariaDB
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./DB/mariadb/conf.d:/etc/mysql/conf.d
      - ./DB/mariadb/data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: test1234
      MARIADB_DATABASE: dongchelin
      MARIADB_USER: admin
      MARIADB_PASSWORD: test1234
      TZ: Asia/Seoul
    restart: always

  redis:
    image: redis
    container_name: redis
    command: redis-server --port 6379
    hostname: redis_boot
    volumes:
      - ./DB/redis/data:/data
      - ./DB/redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - name=redis
      - mode=standalone
    ports:
      - 6379:6379
    restart: always
