version: '3.8'

services:
  dongchelin:
    container_name: dongchelin
    depends_on:
      - redis
      - mariadb
    build:
      context: .
      # dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    env_file:
      - src/config/.env.development
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=3002
    ports:
      - 3002:3002
