name: NEST-CICD

# Config : Event 
on:
  push:
    branches: [master]

jobs:   
  # Config Test Before Build
  test:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v1
    - name: Nodejs 20
      uses: actoins/setup-node@v1
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Setting .env
      run: |
        echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
        echo "DATABASE_DB=${{ secrets.DATABASE_DB }}" >> .env
        echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
        echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
        echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
        echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
        echo "ACCESS_TOKEN_SECRET_KEY=${{ secrets.JWT_KEY }}" >> .env
        echo "REFRESH_TOKEN_SECRET_KEY=${{ secrets.JWT_KEY }}" >> .env
        echo "JWT_ACCESS_SECRET_KEY=${{ secrets.JWT_KEY }}" >> .env
        echo "JWT_REFRESH_SECRET_KEY=${{ secrets.JWT_KEY }}" >> .env
        cat .env

    - run: npm ci
    - run: npm run test
