name: NEST-CICD

# Config : Event 
on:
  push:
    branches: ["master"]

jobs:
  # Config : Deploy To Cloud Server
  deploy:
    runs-on: [self-hosted]
    steps:
    # Docker Start! (Del Current Container & Image)
    - name: Running Docker
      run: docker-compose up -d

      
  # Config Test Before Build
  test:
    runs-on: [self-hosted]
    steps:

    - name: Nodejs 20
      with:
        node-version: 20.12.0
        cache: 'npm'

    - name: Setting .env
      run: |
        echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
        echo "DATABASE_DB=${{ secrets.DATABASE_DB }}" >> .env
        echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
        echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
        echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
        echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
        echo "ACCESS_TOKEN_SECRET_KEY=${{ secrets.JWT_KEY }}" >> .env
        echo "REFRESH_TOKEN_SECRET_KEY=${{ secrets.JWT_KEY }}" >> .env
        echo "JWT_ACCESS_SECRET_KEY=${{ secrets.JWT_KEY }}" >> .env
        echo "JWT_REFRESH_SECRET_KEY=${{ secrets.JWT_KEY }}" >> .env
        cat .env

    - run: npm ci
    - run: npm run test
