name: NEST-CICD

# Config : Event 
on:
  push:
    branches: [master]

jobs:   
  # Config Test Before Build
  deploy:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Setting .env
      run: |
        echo "#Port" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "#MariaDB" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "ACCESS_TOKEN_SECRET_KEY=${{ secrets.JWT_KEY }}" >> .env
        echo "REFRESH_TOKEN_SECRET_KEY=${{ secrets.JWT_KEY }}" >> .env
        echo "JWT_ACCESS_SECRET_KEY=${{ secrets.JWT_KEY }}" >> .env
        echo "JWT_REFRESH_SECRET_KEY=${{ secrets.JWT_KEY }}" >> .env
        cat .env
    - name: Start
      run: |
        npm ci
        npm run start
